### ISSUE TITLE
Easy setup - Closing single quote.

### ISSUE THREAD

**Issue by boudie65** [tjbotcz/tjbotcz_lite#6]
Please add a Closing single quote on this line. The easy.js is creating a none working credentials file
 https://github.com/tjbotcz/tjbotcz_lite/blob/697820fef78bfb5da15a36ec62289b4318a43400/easy.js#L72
Same goes for 
https://github.com/tjbotcz/tjbotcz_lite/blob/697820fef78bfb5da15a36ec62289b4318a43400/easy.js#L79

**Comment by tjbotcz** [comment]
Corrected. Thanks.
